import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
  'intro',
  'getting-started',
  'algorithms',

  {
    type: 'category',
    label: 'Architecture & Components',
    items: [
      'architecture',
      'computation',
      'agent',
      'manager',
      'cli',
      {
        type: 'category',
        label: 'Hardware Abstraction Layer',
        items: [
          'hal',
          'cloud',
        ],
      },
    ],
  },

  {
    type: 'category',
    label: 'Trusted Execution',
    items: [
      'tee',
      {
        type: 'category',
        label: 'Attestation',
        items: [
          'attestation-introduction',
          'attestation-attestation-report',
          'attestation-measured-boot',
          'atls',
          'public-cloud-attestation-framework',
          {
            type: 'category',
            label: 'Verification',
            items: [
              'public-cloud-attestation-verification',
            ],
          },
        ],
      },
    ],
  },

  'developer-guide',
],

  
};

export default sidebars;
